[package]
name = "autocontext"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "printing", "visit-mut"] }
